import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: 9,
  tables: [
    tableSchema({
      name: 'categories',
      columns: [
        { name: 'name', type: 'string', isIndexed: true },
        { name: 'description', type: 'string' },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'deleted_at', type: 'number' },
        { name: 'device_id', type: 'string', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'users',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'email', type: 'string', isIndexed: true },
        { name: 'pin', type: 'string' },
        { name: 'pin_hash', type: 'string' },
        { name: 'role', type: 'string', isIndexed: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'deleted_at', type: 'number' },
        { name: 'device_id', type: 'string', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'products',
      columns: [
        { name: 'name', type: 'string', isIndexed: true },
        { name: 'price', type: 'number' },
        { name: 'stock', type: 'number' },
        { name: 'barcode', type: 'string', isIndexed: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'deleted_at', type: 'number' },
        { name: 'device_id', type: 'string', isIndexed: true },
        { name: 'cost_price', type: 'number' },
        { name: 'category_id', type: 'string', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'orders',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'shift_id', type: 'string', isIndexed: true },
        { name: 'total_price', type: 'number' },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'payment_method', type: 'string' },
        { name: 'created_at', type: 'number', isIndexed: true },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'deleted_at', type: 'number' },
        { name: 'device_id', type: 'string', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'customers',
      columns: [
        { name: 'name', type: 'string', isIndexed: true },
        { name: 'phone', type: 'string', isIndexed: true },
        { name: 'email', type: 'string', isIndexed: true },
        { name: 'address', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'deleted_at', type: 'number' },
        { name: 'device_id', type: 'string', isIndexed: true },
      ],
    }),
    tableSchema({
      name: 'order_items',
      columns: [
        { name: 'order_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'price', type: 'number' },
        { name: 'quantity', type: 'number' },
        { name: 'updated_at', type: 'number', isIndexed: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'deleted_at', type: 'number' },
        { name: 'device_id', type: 'string', isIndexed: true },
        { name: 'cost_price', type: 'number' },
      ],
    }),
  ],
});
